("=" *30)
("         FUNDAMENTOS     ")
("="*30)
print()
print("ola turma! ")
print("0 nome do curso ")
print("estou começando  a programar em python!")

nome = ("Digite o nome")
idade =("Digite a idade ")
cidade =("Digite a cidade")
curso = ("Digite o nome do curso")

print = ("meu nome é´, nome")
print = ("minha, idade")